// Rótulos das respostas da ficha, usados no histórico de edições (FICHA_EDITADA)
export const ADOPTION_FORM_FIELD_LABELS: Record<string, string> = {
  fullName: 'Nome completo',
  email: 'Email',
  birthDate: 'Data de nascimento',
  cpf: 'CPF',
  phone: 'Telefone',
  phoneIsWhatsapp: 'Telefone é WhatsApp',
  occupation: 'Profissão',
  zipCode: 'CEP',
  street: 'Rua',
  number: 'Número',
  complement: 'Complemento',
  neighborhood: 'Bairro',
  city: 'Cidade',
  state: 'UF',
  hasPets: 'Tem outros animais',
  petsCount: 'Quantidade de animais',
  petsDescription: 'Descrição dos animais',
  petsNeutered: 'Animais castrados',
  petsNotNeuteredReason: 'Motivo de não castrar',
  knowsNeuteringImportance: 'Importância da castração',
  petsVaccinesUpToDate: 'Vacinas em dia',
  catFivFelvTested: 'Teste FIV/FeLV',
  awareOfAdaptationPeriod: 'Período de adaptação',
  desiredAnimal: 'Animal desejado',
  sawAdOn: 'Onde viu a divulgação',
  sawAdOnOther: 'Outro local da divulgação',
  canAffordCare: 'Arcar com os custos',
  intendedFood: 'Ração pretendida',
  hasTrustedClinic: 'Clínica de confiança',
  trustedClinicName: 'Nome da clínica',
  residenceType: 'Tipo de residência',
  condoPetPolicy: 'Posição do condomínio',
  windowsScreened: 'Janelas teladas',
  housingOwnership: 'Tipo de imóvel',
  housingOwnershipOther: 'Outro tipo de imóvel',
  adultsCount: 'Quantidade de adultos',
  childrenCount: 'Quantidade de crianças',
  childrenAges: 'Idade das crianças',
  everyoneAgrees: 'Todos concordam',
  disagreementPlan: 'Plano em caso de discordância',
  hoursAlonePerDay: 'Horas sozinho por dia',
  caretakerWhenTraveling: 'Cuidador em viagens',
  pregnancyOpinion: 'Opinião sobre gravidez',
  plansToMove: 'Pretende se mudar',
  moveAnimalPlan: 'Plano para o animal na mudança',
  someoneAllergic: 'Alergia na casa',
  allergyPlan: 'Plano em caso de alergia',
  hasSurrenderedPet: 'Já doou algum animal',
  surrenderDetails: 'Circunstâncias da doação',
  hasLostPetOutside: 'Já perdeu algum animal',
  lostPetDetails: 'Circunstâncias da perda',
  hadRecentPetDeath: 'Morte recente de animal',
  recentDeathDetails: 'Circunstâncias da morte',
  awareOfLongevity: 'Ciente da longevidade',
  willReportChanges: 'Informar mudanças',
  willNotRehomeWithoutNotice: 'Não repassar sem avisar',
  idealAnimal: 'Animal ideal',
  thinkingSince: 'Desde quando pensa em adotar',
  awareOfEvaluationProcess: 'Ciente do processo de avaliação',
};
